version: 2
jobs:
  build: 
    working_directory: ~/openedx-theme
    docker: 
      - image: circleci/python:2.7
    branches:
      only: 
        - develop
        - /feature.*/
        - /bug.*/
    steps: 
      - checkout
      - run: echo '[edxapp-server]' > ~/inventory
      - run: echo $STAGING_SERVER >> ~/inventory
      - run: 
          name: Deploy to staging
          command: ~/openedx-theme/deploy/deploy_staging.sh
          no_output_timeout: 30m
