version: 2
jobs:
  build: 
    working_directory: ~/openedx-theme
    docker: 
      - image: circleci/python:2.7
    branches:
      only: 
        - hawthorn/dev
    steps: 
      - checkout
      - run: echo '[edxapp-server]' > ~/inventory
      - run: echo $DEV_SERVER >> ~/inventory
      - run: 
          name: Deploy to Dev Instance
          command: ~/openedx-theme/deploy/deploy_staging.sh
          no_output_timeout: 30m
